In [5]:
import numpy as np
from keras import Input
from keras.backend import cast_to_floatx
from keras.callbacks import ModelCheckpoint, EarlyStopping
from keras.engine import Model
from keras.layers import Dense, Dropout, regularizers, concatenate
from keras.models import load_model
from keras.models import load_model

Dense implements the operation: output = activation(dot(input, kernel) + bias) where activation is the element-wise activation function passed as the activation argument, kernel is a weights matrix created by the layer, and bias is a bias vector created by the layer (only applicable if use_bias is True).

## Dense layer

Dense implements the operation:

```
output = activation(dot(input, kernel) + bias)
```

where `activation` is the element-wise activation function passed as the activation argument,
`kernel` is a weights matrix created by the layer, and `bias` is a bias vector created by
the layer (only applicable if `use_bias` is `True`).



### One Neuron Layer

Output is just a dot product of the weights $\boldsymbol{w}$ (1D vector) and input $\boldsymbol{x}$ (1D vector)
passed in to the activation function $f$. The weights and input size is $N=2$ in our case. Bias is $b$ (scalar value).

$$f(\boldsymbol{x} \cdot \boldsymbol{w} + b) = f\left(\sum_{i=0}^{N}w_{i}x_{i} + b \right)$$

In [35]:
# activation f(x) = x

i = Input(shape=(2,), name='main')
d = Dense(1)(i)
m = Model(i, d)
m.layers[1].set_weights([np.array([[1], [1]]), np.array([0])])    
m.compile('rmsprop', 'mse')

# just a sum of input (weights are ones)
x = np.array([[2, 2]])
m.predict(x)

array([[4.]], dtype=float32)

In [36]:
# activation f(x) = relu(x)

i = Input(shape=(2,), name='main')
d = Dense(1, activation='relu')(i)
m = Model(i, d)
m.layers[1].set_weights([np.array([[1], [1]]), np.array([0])])    
m.compile('rmsprop', 'mse')

# 0, input sum is < 0
x = np.array([[-20, 2]])
print(m.predict(x))

# just a sum of input - weights are ones and the input sum is > 0
x = np.array([[20, 2]])
print(m.predict(x))

[[0.]]
[[22.]]


### 2 Neuron Layer

Assume an input of shape $N=2$ and a dense layer with two neurons with weights

$$\boldsymbol{W} = \begin{bmatrix}1 & 2 \\ 1 & 2\end{bmatrix}$$

where each row represents one neuron. The bias vector is

$$\boldsymbol{b}=\begin{bmatrix}0 \\ 0\end{bmatrix}$$

and the actiovation function

$$f(x) = x.$$

The input vector is

$$\boldsymbol{x} = \begin{bmatrix}2 & 2\end{bmatrix}.$$

Calculating the dot product of the input and one row of the weight matrix and applying the activation function
produces one value of the output vector of the layer. Let $\hat{f}$ denote the element-wise application of the activation function $f$. The output of the layer is then

$$
\hat{f}(\boldsymbol{x} \cdot \boldsymbol{W} + \boldsymbol{b}) =
\begin{bmatrix}
    f(\boldsymbol{x} \cdot \boldsymbol{w}_{1} + b_{1}) \\
    f(\boldsymbol{x} \cdot \boldsymbol{w}_{2} + b_{2})
\end{bmatrix} =
\begin{bmatrix}
    f(2 \cdot 1 + 2 \cdot 1 + 0) \\
    f(2 \cdot 2 + 2 \cdot 2 + 0)
\end{bmatrix} =
\begin{bmatrix}
    4 & 8
\end{bmatrix}$$

where $\boldsymbol{x}$ is the input vector, $\boldsymbol{w}_{1}$ and $\boldsymbol{w}_{2}$ are the weight vectors for the first
and second neuron; $b_{1}$ and $b_{2}$ are biases for the first and second neuron.

$$
\boldsymbol{x}\cdot\boldsymbol{W} + \boldsymbol{b}=
\begin{bmatrix}
    2 & 2
\end{bmatrix}
\begin{bmatrix}
    1 & 2 \\
    1 & 2
\end{bmatrix} +
\begin{bmatrix}
    0 \\ 0
\end{bmatrix} =
\begin{bmatrix}
    4 & 8
\end{bmatrix}$$

$$
\hat{f}(\boldsymbol{x} \cdot \boldsymbol{W} + \boldsymbol{b}) =
\begin{bmatrix}
    f(4) & f(8)
\end{bmatrix} =
\begin{bmatrix}
    4 & 8
\end{bmatrix}$$

In [45]:
# activation f(x) = x

i = Input(shape=(2,), name='main')
d = Dense(2)(i)
m = Model(i, d)
W = np.array([[1, 2], [1, 2]])
m.layers[1].set_weights([W, np.array([0, 0])])    
m.compile('rmsprop', 'mse')

# just a sum of input (weights are ones)
x = np.array([[2, 2]])
m.predict(x)

array([[4., 8.]], dtype=float32)

### Concatenate Layer

In [37]:
i = [Input(shape=(2,), name='main'), Input(shape=(3,), name='secondary')]
c = concatenate(i)
m = Model(i, c)
m.compile('rmsprop', 'mse')

x_main = np.array([[1, 1]])
x_secondary = np.array([[-1, -1, -1]])

print(m.predict({'main': x_main, 'secondary': x_secondary}))

[[ 1.  1. -1. -1. -1.]]


### Dropout Layer

In [80]:
# effects only training?

i = Input(shape=(2,), name='main')
d = Dropout(1, seed=0)(i)
m = Model(i, d)
m.compile('rmsprop', 'mse')

# just a sum of input (weights are ones)
x = np.array([[1] * 2])
m.predict(x)

array([[1., 1.]], dtype=float32)